### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by il-ponz** [Gkiokan/hb-store-cdn-cli-server#1]
when starting or stopping service on ubuntu 22.04 i get the following error in console
` [Server] Stop the server (node:428118) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /snapshot/HB-Store-CDN-CLI-Server/node_modules/cli-table/lib/index.js:188:27
    at Array.forEach (<anonymous>)
    at generateRow (/snapshot/HB-Store-CDN-CLI-Server/node_modules/cli-table/lib/index.js:187:11)
    at /snapshot/HB-Store-CDN-CLI-Server/node_modules/cli-table/lib/index.js:281:16
    at Table.forEach (<anonymous>)
    at Table.toString (/snapshot/HB-Store-CDN-CLI-Server/node_modules/cli-table/lib/index.js:264:10)
    at Object.showList (/snapshot/HB-Store-CDN-CLI-Server/build/cli.js)
    at Object.sendFiles (/snapshot/HB-Store-CDN-CLI-Server/build/server.js)
    at Object.addFilesFromBasePath (/snapshot/HB-Store-CDN-CLI-Server/build/server.js)
    at runMicrotasks (<anonymous>)
(Use `hb-store-cdn-cli-server-linux --trace-warnings ...` to show where the warning was created)
(node:428118) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:428118) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by Gkiokan** [comment]
Thanks for the report mate. 

This should be fixed in the [Release v1.2.0](https://github.com/Gkiokan/hb-store-cdn-cli-server/releases/tag/v1.2.0). 

Please try it out and let me know if the error still exists.
